project_id = "ihzfwkiqkwbgbgjjbeih"

[functions.agent-chat]
verify_jwt = false

[functions.squad-consultant]
verify_jwt = false

[functions.admin-agent]
verify_jwt = false

[functions.cyber-security-agent]
verify_jwt = false

[functions.cfo-agent]
verify_jwt = false

[functions.growth-agent]
verify_jwt = false

[functions.support-chat]
verify_jwt = false