import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Instagram, Youtube, Sparkles, Calendar, CheckCircle2,
  Clock, Zap, FileText, Bot, Loader2, RefreshCw
} from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import HelpTooltip from "@/components/HelpTooltip";

const ContentPipelinePanel = () => {
  const { user } = useAuth();
  const [generating, setGenerating] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState("instagram");

  // Fetch content tasks (scripts generated by content agents)
  const { data: contentTasks = [], refetch } = useQuery({
    queryKey: ["content-pipeline", user?.id],
    queryFn: async () => {
      const { data } = await supabase
        .from("agent_tasks")
        .select("*")
        .eq("user_id", user!.id)
        .in("category", ["content_instagram", "content_youtube", "content"])
        .order("created_at", { ascending: false })
        .limit(50);
      return data || [];
    },
    enabled: !!user,
  });

  const instagramContent = contentTasks.filter((t: any) =>
    t.category === "content_instagram" || t.title?.toLowerCase().includes("instagram")
  );
  const youtubeContent = contentTasks.filter((t: any) =>
    t.category === "content_youtube" || t.title?.toLowerCase().includes("youtube")
  );

  const requestContent = async (platform: "instagram" | "youtube") => {
    if (!user) return;
    setGenerating(platform);

    try {
      // Get tenant_id
      const { data: tenantId } = await supabase.rpc("get_user_tenant_id", { _user_id: user.id });
      if (!tenantId) throw new Error("Tenant não encontrado");

      const titles: Record<string, string> = {
        instagram: `Roteiro Instagram — ${new Date().toLocaleDateString("pt-BR")}`,
        youtube: `Roteiro YouTube — ${new Date().toLocaleDateString("pt-BR")}`,
      };

      const descriptions: Record<string, string> = {
        instagram: "Gere um roteiro criativo para post/reel do Instagram, incluindo: gancho, desenvolvimento, CTA, hashtags e sugestão visual.",
        youtube: "Gere um roteiro completo para vídeo YouTube, incluindo: título SEO, thumbnail description, intro (hook), 3-5 seções, CTA e descrição do vídeo.",
      };

      await supabase.from("agent_tasks").insert({
        user_id: user.id,
        tenant_id: tenantId,
        title: titles[platform],
        description: descriptions[platform],
        priority: "high",
        category: `content_${platform}`,
        status: "open",
      });

      toast.success(`Roteiro ${platform === "instagram" ? "Instagram" : "YouTube"} solicitado!`);
      refetch();
    } catch (err) {
      toast.error("Erro ao solicitar conteúdo.");
    } finally {
      setGenerating(null);
    }
  };

  const today = new Date().toISOString().split("T")[0];
  const todayInstagram = instagramContent.filter((t: any) => t.created_at?.startsWith(today)).length;
  const todayYoutube = youtubeContent.filter((t: any) => t.created_at?.startsWith(today)).length;

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });
  };

  const ContentList = ({ items }: { items: any[] }) => (
    <ScrollArea className="h-[400px]">
      <div className="space-y-2">
        {items.length === 0 ? (
          <div className="text-center py-12 text-muted-foreground text-sm">
            <FileText className="h-8 w-8 mx-auto mb-2 text-muted-foreground/30" />
            Nenhum roteiro gerado ainda. Clique em "Gerar" para começar!
          </div>
        ) : items.map((task: any) => (
          <Card key={task.id} className="p-3 glass-card border-border/10 group hover:bg-card/80 transition-colors">
            <div className="flex items-start gap-3">
              <div className={`p-1.5 rounded-lg shrink-0 ${
                task.status === "completed" || task.status === "done"
                  ? "bg-emerald-500/10"
                  : "bg-primary/10"
              }`}>
                {task.status === "completed" || task.status === "done"
                  ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                  : <Clock className="h-3.5 w-3.5 text-primary" />
                }
              </div>
              <div className="flex-1 min-w-0">
                <span className="text-sm font-medium truncate block">{task.title}</span>
                {task.description && (
                  <p className="text-xs text-muted-foreground line-clamp-2 mt-0.5">{task.description}</p>
                )}
                <div className="flex items-center gap-2 mt-1.5">
                  <span className="text-[10px] text-muted-foreground">{formatDate(task.created_at)}</span>
                  <Badge variant={task.status === "completed" || task.status === "done" ? "default" : "secondary"} className="text-[9px] h-4">
                    {task.status}
                  </Badge>
                </div>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </ScrollArea>
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="font-display text-xl font-bold flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          Pipeline de Conteúdo
          <HelpTooltip id="content-pipeline" text="Solicite e acompanhe roteiros diários para Instagram e YouTube. O sistema também gera automaticamente via event-loop." size={14} />
        </h2>
        <p className="text-sm text-muted-foreground mt-1">
          Roteiros diários para suas redes sociais, gerados pelos agentes de conteúdo.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { label: "Instagram Hoje", value: todayInstagram, icon: Instagram, color: "text-pink-500" },
          { label: "YouTube Hoje", value: todayYoutube, icon: Youtube, color: "text-red-500" },
          { label: "Total Instagram", value: instagramContent.length, icon: Instagram, color: "text-pink-500/70" },
          { label: "Total YouTube", value: youtubeContent.length, icon: Youtube, color: "text-red-500/70" },
        ].map((card, i) => (
          <motion.div
            key={card.label}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
          >
            <Card className="p-4 glass-card border-border/10">
              <div className="flex items-center gap-2 mb-1">
                <card.icon className={`h-4 w-4 ${card.color}`} />
                <span className="text-[11px] text-muted-foreground font-medium">{card.label}</span>
              </div>
              <span className="text-2xl font-display font-bold">{card.value}</span>
            </Card>
          </motion.div>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="flex gap-3">
        <Button
          variant="outline"
          className="gap-2 border-pink-500/20 text-pink-500 hover:bg-pink-500/10"
          onClick={() => requestContent("instagram")}
          disabled={generating !== null}
        >
          {generating === "instagram" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Instagram className="h-4 w-4" />}
          Gerar Roteiro Instagram
        </Button>
        <Button
          variant="outline"
          className="gap-2 border-red-500/20 text-red-500 hover:bg-red-500/10"
          onClick={() => requestContent("youtube")}
          disabled={generating !== null}
        >
          {generating === "youtube" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Youtube className="h-4 w-4" />}
          Gerar Roteiro YouTube
        </Button>
      </div>

      {/* Content Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="bg-muted/30 p-1 gap-1">
          <TabsTrigger value="instagram" className="text-xs gap-1.5">
            <Instagram className="h-3.5 w-3.5" /> Instagram ({instagramContent.length})
          </TabsTrigger>
          <TabsTrigger value="youtube" className="text-xs gap-1.5">
            <Youtube className="h-3.5 w-3.5" /> YouTube ({youtubeContent.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="instagram">
          <ContentList items={instagramContent} />
        </TabsContent>
        <TabsContent value="youtube">
          <ContentList items={youtubeContent} />
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default ContentPipelinePanel;
