
INSERT INTO public.agents_catalog (slug, name, department, squad, responsibilities) VALUES
('content_strategist', 'Content Strategist', 'marketing', 'content_squad', '["Planejamento editorial","Calendário de conteúdo","Análise de gaps"]'::jsonb),
('blog_writer', 'Blog Writer', 'marketing', 'content_squad', '["Artigos SEO","Posts longos","Guest posts"]'::jsonb),
('social_media_agent', 'Social Media Agent', 'marketing', 'content_squad', '["Posts redes sociais","Engajamento","Calendário social"]'::jsonb),
('video_script_agent', 'Video Script Agent', 'marketing', 'content_squad', '["Roteiros Reels/Shorts","Storyboards","Hooks de vídeo"]'::jsonb),
('content_performance', 'Content Performance Analyst', 'marketing', 'content_squad', '["Métricas de conteúdo","Attribution","ROI de conteúdo"]'::jsonb),
('media_buyer', 'Media Buyer', 'marketing', 'ads_squad', '["Compra de mídia","Budget allocation","Otimização cross-platform"]'::jsonb),
('ad_copywriter', 'Ad Copywriter', 'marketing', 'ads_squad', '["Copy de anúncios","Headlines A/B","Ad creatives briefing"]'::jsonb),
('campaign_manager', 'Campaign Manager', 'marketing', 'ads_squad', '["Setup de campanhas","Audience targeting","Bid strategy"]'::jsonb),
('retargeting_specialist', 'Retargeting Specialist', 'marketing', 'ads_squad', '["Audiências lookalike","Remarketing sequences","Pixel optimization"]'::jsonb),
('seo_strategist', 'SEO Strategist', 'marketing', 'seo_squad', '["Estratégia SEO global","Keyword research","Roadmap de otimização"]'::jsonb),
('technical_seo', 'Technical SEO Agent', 'marketing', 'seo_squad', '["Core Web Vitals","Crawlability","Schema markup"]'::jsonb),
('link_builder', 'Link Builder', 'marketing', 'seo_squad', '["Outreach para backlinks","Digital PR","Guest posting strategy"]'::jsonb),
('content_seo_writer', 'Content SEO Writer', 'marketing', 'seo_squad', '["Conteúdo otimizado","Topic clusters","Internal linking"]'::jsonb),
('brand_strategist', 'Brand Strategist', 'marketing', 'brand_strategy_squad', '["Posicionamento de marca","Brand guidelines","Competitive positioning"]'::jsonb),
('positioning_agent', 'Positioning Agent', 'marketing', 'brand_strategy_squad', '["Análise de mercado","Diferenciação","Value proposition"]'::jsonb),
('visual_identity', 'Visual Identity Agent', 'marketing', 'brand_strategy_squad', '["Design system","Templates visuais","Brand consistency"]'::jsonb),
('brand_voice_writer', 'Brand Voice Writer', 'marketing', 'brand_strategy_squad', '["Tom de voz","Messaging framework","Copy guidelines"]'::jsonb),
('campaign_optimizer', 'Campaign Optimizer', 'marketing', 'campaign_optimization_squad', '["Otimização multicanal","Budget reallocation","Performance tuning"]'::jsonb),
('ab_test_agent', 'A/B Test Agent', 'marketing', 'campaign_optimization_squad', '["Design de experimentos","Statistical significance","Test analysis"]'::jsonb),
('attribution_analyst', 'Attribution Analyst', 'marketing', 'campaign_optimization_squad', '["Multi-touch attribution","Channel mix modeling","Customer journey"]'::jsonb),
('budget_allocator', 'Budget Allocator', 'marketing', 'campaign_optimization_squad', '["Budget optimization","ROI forecasting","Channel efficiency"]'::jsonb),
('influencer_mgr', 'Influencer Manager', 'marketing', 'influencer_pr_squad', '["Scout de influencers","Negociação","Campaign tracking"]'::jsonb),
('pr_agent', 'PR Agent', 'marketing', 'influencer_pr_squad', '["Press releases","Media relations","Crisis management"]'::jsonb),
('social_proof_mgr', 'Social Proof Manager', 'marketing', 'influencer_pr_squad', '["Depoimentos","Case studies","UGC curation"]'::jsonb),
('traffic_manager', 'Traffic Manager', 'growth', 'paid_traffic_squad', '["Gestão de tráfego pago","Cross-platform strategy","Budget optimization"]'::jsonb),
('google_ads_agent', 'Google Ads Agent', 'growth', 'paid_traffic_squad', '["Search campaigns","Shopping ads","Display network"]'::jsonb),
('meta_ads_agent', 'Meta Ads Agent', 'growth', 'paid_traffic_squad', '["Facebook/Instagram ads","Audience building","Creative testing"]'::jsonb),
('tiktok_ads_agent', 'TikTok Ads Agent', 'growth', 'paid_traffic_squad', '["TikTok campaigns","Spark Ads","Creator marketplace"]'::jsonb),
('sdr_outbound', 'SDR Outbound Lead', 'growth', 'sdr_outbound_squad', '["Estratégia outbound","Cadências multicanal","Team coordination"]'::jsonb),
('sdr_linkedin', 'SDR LinkedIn', 'growth', 'sdr_outbound_squad', '["LinkedIn outreach","InMail sequences","Sales Navigator"]'::jsonb),
('sdr_email_agent', 'SDR Email Agent', 'growth', 'sdr_outbound_squad', '["Cold email sequences","Follow-up automation","Deliverability"]'::jsonb),
('sdr_whatsapp', 'SDR WhatsApp', 'growth', 'sdr_outbound_squad', '["WhatsApp outreach","Qualificação rápida","Follow-up sequences"]'::jsonb),
('sdr_instagram', 'SDR Instagram', 'growth', 'sdr_outbound_squad', '["DM outreach","Story engagement","Social selling"]'::jsonb),
('sdr_inbound', 'SDR Inbound Lead', 'growth', 'sdr_inbound_squad', '["Lead routing","Qualification framework","SLA management"]'::jsonb),
('lead_qualifier', 'Lead Qualifier', 'growth', 'sdr_inbound_squad', '["BANT qualification","Discovery calls","Lead scoring refinement"]'::jsonb),
('lead_scorer', 'Lead Scorer', 'growth', 'sdr_inbound_squad', '["Lead scoring models","Behavioral tracking","Score calibration"]'::jsonb),
('mql_processor', 'MQL Processor', 'growth', 'sdr_inbound_squad', '["MQL validation","Data enrichment","CRM handoff"]'::jsonb),
('partnership_hunter', 'Partnership Hunter', 'growth', 'partnerships_squad', '["Identificação de parceiros","Outreach","Negociação"]'::jsonb),
('affiliate_manager', 'Affiliate Manager', 'growth', 'partnerships_squad', '["Programa de afiliados","Comissões","Performance tracking"]'::jsonb),
('comarketing_agent', 'Co-Marketing Agent', 'growth', 'partnerships_squad', '["Campanhas conjuntas","Webinars","Content collaboration"]'::jsonb),
('plg_strategist', 'PLG Strategist', 'growth', 'plg_squad', '["Growth strategy","Viral loops","Freemium optimization"]'::jsonb),
('onboarding_optimizer', 'Onboarding Optimizer', 'growth', 'plg_squad', '["Onboarding flows","Activation metrics","First value time"]'::jsonb),
('activation_agent', 'Activation Agent', 'growth', 'plg_squad', '["Feature adoption","Aha moment triggers","User nudges"]'::jsonb),
('retention_analyst', 'Retention Analyst', 'growth', 'plg_squad', '["Cohort analysis","Churn prediction","Retention campaigns"]'::jsonb),
('community_mgr', 'Community Manager', 'growth', 'community_squad', '["Gestão de comunidade","Engagement programs","Member onboarding"]'::jsonb),
('forum_moderator', 'Forum Moderator', 'growth', 'community_squad', '["Moderação","Content quality","Community guidelines"]'::jsonb),
('ambassador_agent', 'Ambassador Program Agent', 'growth', 'community_squad', '["Programa de embaixadores","Recognition","Advocacy"]'::jsonb),
('ugc_curator', 'UGC Curator', 'growth', 'community_squad', '["User-generated content","Showcase","Permissions"]'::jsonb),
('product_strategist', 'Product Strategist', 'product', 'product_strategy_squad', '["Product vision","Roadmap planning","Stakeholder alignment"]'::jsonb),
('roadmap_manager', 'Roadmap Manager', 'product', 'product_strategy_squad', '["Roadmap updates","Timeline tracking","Dependency mapping"]'::jsonb),
('competitive_analyst', 'Competitive Analyst', 'product', 'product_strategy_squad', '["Competitor monitoring","Feature comparison","Market gaps"]'::jsonb),
('market_research_agent', 'Market Research Agent', 'product', 'product_strategy_squad', '["User interviews analysis","Market sizing","Trend analysis"]'::jsonb),
('ux_researcher', 'UX Researcher', 'product', 'ux_research_squad', '["Research planning","Study design","Insights synthesis"]'::jsonb),
('user_interview_agent', 'User Interview Agent', 'product', 'ux_research_squad', '["Interview scripts","User recruitment","Transcription analysis"]'::jsonb),
('survey_analyst', 'Survey Analyst', 'product', 'ux_research_squad', '["Survey design","Data analysis","Statistical insights"]'::jsonb),
('usability_tester', 'Usability Tester', 'product', 'ux_research_squad', '["Usability tests","Heuristic evaluation","Accessibility audit"]'::jsonb),
('product_data_analyst', 'Data Analyst', 'product', 'data_analytics_squad', '["Product analytics","Dashboard creation","Trend identification"]'::jsonb),
('product_metrics_agent', 'Product Metrics Agent', 'product', 'data_analytics_squad', '["KPI tracking","North star metric","Feature metrics"]'::jsonb),
('cohort_analyst', 'Cohort Analyst', 'product', 'data_analytics_squad', '["Cohort analysis","Retention curves","Behavioral segmentation"]'::jsonb),
('funnel_analyst', 'Funnel Analyst', 'product', 'data_analytics_squad', '["Conversion funnels","Drop-off analysis","Optimization recommendations"]'::jsonb),
('experimentation_agent', 'Experimentation Agent', 'product', 'data_analytics_squad', '["A/B test design","Feature flags","Statistical analysis"]'::jsonb),
('technical_writer', 'Technical Writer', 'product', 'engineering_support_squad', '["Documentation","API docs","Knowledge base"]'::jsonb),
('api_doc_agent', 'API Documentation Agent', 'product', 'engineering_support_squad', '["API reference","Code examples","SDK guides"]'::jsonb),
('qa_analyst', 'QA Analyst', 'product', 'engineering_support_squad', '["Test planning","Bug verification","Regression testing"]'::jsonb),
('bug_tracker', 'Bug Tracker', 'product', 'engineering_support_squad', '["Bug triage","Priority classification","Resolution tracking"]'::jsonb),
('release_notes_agent', 'Release Notes Agent', 'product', 'engineering_support_squad', '["Changelog generation","Release communications","Feature announcements"]'::jsonb),
('ai_research_agent', 'AI Research Agent', 'product', 'ai_innovation_squad', '["Model evaluation","Capability assessment","Research papers"]'::jsonb),
('trend_scout', 'Trend Scout', 'product', 'ai_innovation_squad', '["Technology trends","Market signals","Early adoption"]'::jsonb),
('innovation_lab', 'Innovation Lab Agent', 'product', 'ai_innovation_squad', '["Proof of concepts","Prototype development","Feasibility analysis"]'::jsonb),
('prototype_tester', 'Prototype Tester', 'product', 'ai_innovation_squad', '["Prototype testing","User feedback","Iteration recommendations"]'::jsonb),
('tech_evaluator', 'Technology Evaluator', 'product', 'ai_innovation_squad', '["Vendor assessment","Tool comparison","Build vs buy analysis"]'::jsonb),
('enterprise_ae', 'Enterprise Account Executive', 'sales', 'enterprise_sales_squad', '["Enterprise deals","Stakeholder mapping","Proposal customization"]'::jsonb),
('solution_architect', 'Solution Architect', 'sales', 'enterprise_sales_squad', '["Technical discovery","Solution design","Integration planning"]'::jsonb),
('proposal_gen', 'Proposal Generator', 'sales', 'enterprise_sales_squad', '["Proposal creation","Pricing models","ROI calculations"]'::jsonb),
('contract_negotiator', 'Contract Negotiator', 'sales', 'enterprise_sales_squad', '["Contract terms","Legal review","SLA negotiation"]'::jsonb),
('midmarket_ae', 'Mid-Market AE', 'sales', 'midmarket_sales_squad', '["Mid-market deals","Demo execution","Pipeline management"]'::jsonb),
('demo_specialist', 'Demo Specialist', 'sales', 'midmarket_sales_squad', '["Demo preparation","Use case customization","Demo follow-up"]'::jsonb),
('pricing_analyst', 'Pricing Analyst', 'sales', 'midmarket_sales_squad', '["Pricing strategy","Discount approval","Competitive pricing"]'::jsonb),
('deal_desk', 'Deal Desk Agent', 'sales', 'midmarket_sales_squad', '["Deal structuring","Approval workflow","Contract generation"]'::jsonb),
('smb_closer', 'SMB Closer', 'sales', 'smb_sales_squad', '["High-velocity closing","Objection handling","Quick proposals"]'::jsonb),
('self_serve_optimizer', 'Self-Serve Optimizer', 'sales', 'smb_sales_squad', '["Checkout optimization","Friction removal","Payment flows"]'::jsonb),
('trial_converter', 'Trial Converter', 'sales', 'smb_sales_squad', '["Trial engagement","Feature adoption nudges","Conversion incentives"]'::jsonb),
('upgrade_agent', 'Upgrade Agent', 'sales', 'smb_sales_squad', '["Upsell opportunities","Plan comparison","Value demonstration"]'::jsonb),
('crm_manager', 'CRM Manager', 'sales', 'sales_ops_squad', '["CRM hygiene","Automation workflows","Data integrity"]'::jsonb),
('sales_forecaster', 'Sales Forecaster', 'sales', 'sales_ops_squad', '["Revenue forecasting","Pipeline analysis","Trend modeling"]'::jsonb),
('territory_planner', 'Territory Planner', 'sales', 'sales_ops_squad', '["Territory design","Quota setting","Balance optimization"]'::jsonb),
('sales_enablement', 'Sales Enablement Agent', 'sales', 'sales_ops_squad', '["Sales collateral","Training content","Competitive cards"]'::jsonb),
('hunter_linkedin', 'Hunter - Prospecção LinkedIn', 'sales', 'sales_ops_squad', '["Busca de leads no LinkedIn","Icebreakers com IA","Envio automático de convites"]'::jsonb),
('channel_manager', 'Channel Manager', 'sales', 'channel_sales_squad', '["Channel strategy","Partner relationships","Revenue tracking"]'::jsonb),
('reseller_recruiter', 'Reseller Recruiter', 'sales', 'channel_sales_squad', '["Reseller identification","Onboarding","Certification"]'::jsonb),
('channel_revenue', 'Channel Revenue Analyst', 'sales', 'channel_sales_squad', '["Channel analytics","Partner performance","ROI analysis"]'::jsonb),
('voice_ai', 'Voice AI Agent', 'sales', 'voice_telephony_squad', '["AI voice calls","Natural conversation","Intent detection"]'::jsonb),
('call_analyzer', 'Call Analyzer', 'sales', 'voice_telephony_squad', '["Call transcription","Sentiment analysis","Coaching insights"]'::jsonb),
('script_optimizer', 'Script Optimizer', 'sales', 'voice_telephony_squad', '["Script testing","Objection handling","Conversion optimization"]'::jsonb),
('revenue_analyst', 'Revenue Analyst', 'sales', 'revenue_intel_squad', '["Revenue analytics","MRR/ARR tracking","Revenue trends"]'::jsonb),
('winloss_analyst', 'Win/Loss Analyst', 'sales', 'revenue_intel_squad', '["Win/loss analysis","Competitive patterns","Deal insights"]'::jsonb),
('onboarding_specialist', 'Onboarding Specialist', 'customer_success', 'onboarding_squad', '["Onboarding planning","Kickoff calls","Milestone tracking"]'::jsonb),
('implementation_agent', 'Implementation Agent', 'customer_success', 'onboarding_squad', '["Technical setup","Data migration","Integration config"]'::jsonb),
('training_agent', 'Training Agent', 'customer_success', 'onboarding_squad', '["User training","Workshop facilitation","Training materials"]'::jsonb),
('support_channel', 'Support Channel Agent', 'customer_success', 'support_n1_squad', '["Multi-channel support","Ticket routing","First response"]'::jsonb),
('chat_agent', 'Chat Agent', 'customer_success', 'support_n1_squad', '["Live chat","Instant responses","Quick resolution"]'::jsonb),
('email_support', 'Email Support Agent', 'customer_success', 'support_n1_squad', '["Email support","Detailed responses","Follow-up tracking"]'::jsonb),
('support_lead', 'Technical Support Lead', 'customer_success', 'support_n2n3_squad', '["Complex troubleshooting","Escalation management","Team coordination"]'::jsonb),
('escalation_mgr', 'Escalation Manager', 'customer_success', 'support_n2n3_squad', '["Escalation workflow","Resolution tracking","Communication"]'::jsonb),
('bug_reporter', 'Bug Reporter Agent', 'customer_success', 'support_n2n3_squad', '["Bug documentation","Reproduction steps","Engineering handoff"]'::jsonb),
('integration_support', 'Integration Support Agent', 'customer_success', 'support_n2n3_squad', '["Integration troubleshooting","API support","Webhook debugging"]'::jsonb),
('sla_monitor', 'SLA Monitor', 'customer_success', 'support_n2n3_squad', '["SLA tracking","Breach prevention","Performance reporting"]'::jsonb),
('csm_agent', 'CSM Agent', 'customer_success', 'success_mgmt_squad', '["Account management","Success planning","Relationship building"]'::jsonb),
('health_monitor', 'Health Score Monitor', 'customer_success', 'success_mgmt_squad', '["Health scoring","Risk identification","Intervention triggers"]'::jsonb),
('expansion_agent', 'Expansion Agent', 'customer_success', 'success_mgmt_squad', '["Upsell identification","Cross-sell opportunities","Value realization"]'::jsonb),
('renewal_agent', 'Renewal Agent', 'customer_success', 'success_mgmt_squad', '["Renewal management","Contract terms","Retention offers"]'::jsonb),
('ebr_agent', 'Executive Business Review Agent', 'customer_success', 'success_mgmt_squad', '["QBR preparation","ROI reporting","Strategic recommendations"]'::jsonb),
('knowledge_base_agent', 'Knowledge Base Agent', 'customer_success', 'knowledge_selfservice_squad', '["KB management","Article creation","Content updates"]'::jsonb),
('help_center_writer', 'Help Center Writer', 'customer_success', 'knowledge_selfservice_squad', '["How-to guides","Troubleshooting articles","Video tutorials"]'::jsonb),
('tutorial_creator', 'Tutorial Creator', 'customer_success', 'knowledge_selfservice_squad', '["Step-by-step tutorials","Interactive guides","Walkthrough videos"]'::jsonb),
('chatbot_trainer', 'Chatbot Trainer', 'customer_success', 'knowledge_selfservice_squad', '["Chatbot training","Intent mapping","Response optimization"]'::jsonb),
('selfservice_optimizer', 'Self-Service Optimizer', 'customer_success', 'knowledge_selfservice_squad', '["Self-service metrics","Deflection optimization","User experience"]'::jsonb),
('nps_analyst', 'NPS Analyst', 'customer_success', 'voc_squad', '["NPS campaigns","Score analysis","Follow-up actions"]'::jsonb),
('csat_monitor', 'CSAT Monitor', 'customer_success', 'voc_squad', '["CSAT tracking","Trend analysis","Alert management"]'::jsonb),
('feedback_collector', 'Feedback Collector', 'customer_success', 'voc_squad', '["Feedback collection","Categorization","Product team handoff"]'::jsonb),
('customer_advocacy', 'Customer Advocacy Agent', 'customer_success', 'voc_squad', '["Case studies","Testimonials","Reference program"]'::jsonb),
('digital_accountant', 'Digital Accountant', 'finance', 'accounting_squad', '["Escrituração contábil","Conciliação bancária","Balancete"]'::jsonb),
('accounts_payable', 'Accounts Payable Agent', 'finance', 'accounting_squad', '["Contas a pagar","Vendor payments","Cash flow management"]'::jsonb),
('accounts_receivable', 'Accounts Receivable Agent', 'finance', 'accounting_squad', '["Contas a receber","Collections","Aging analysis"]'::jsonb),
('reconciliation_agent', 'Reconciliation Agent', 'finance', 'accounting_squad', '["Bank reconciliation","GL matching","Discrepancy resolution"]'::jsonb),
('general_ledger', 'General Ledger Agent', 'finance', 'accounting_squad', '["GL maintenance","Journal entries","Period closing"]'::jsonb),
('tax_compliance', 'Tax Compliance Agent', 'finance', 'tax_compliance_squad', '["Obrigações acessórias","SPED/EFD","Apuração de impostos"]'::jsonb),
('tax_content_agent', 'Tax Content Writer', 'finance', 'tax_compliance_squad', '["Conteúdo tributário","Alertas fiscais","Newsletter fiscal"]'::jsonb),
('regulatory_monitor', 'Regulatory Monitor', 'finance', 'tax_compliance_squad', '["Regulatory tracking","Compliance alerts","Impact analysis"]'::jsonb),
('audit_prep', 'Audit Preparation Agent', 'finance', 'tax_compliance_squad', '["Audit documentation","Evidence collection","Compliance testing"]'::jsonb),
('fiscal_analyst', 'Fiscal Analyst', 'finance', 'tax_compliance_squad', '["Tax optimization","Credit identification","Fiscal planning"]'::jsonb),
('ai_cfo', 'CFO Agent', 'finance', 'fpa_squad', '["Financial strategy","Board reporting","Capital allocation"]'::jsonb),
('budget_analyst', 'Budget Analyst', 'finance', 'fpa_squad', '["Budget creation","Variance analysis","Departmental budgets"]'::jsonb),
('financial_forecaster', 'Financial Forecaster', 'finance', 'fpa_squad', '["Revenue forecasting","Scenario modeling","Cash flow projection"]'::jsonb),
('variance_analyst', 'Variance Analyst', 'finance', 'fpa_squad', '["Actual vs budget","Root cause analysis","Corrective actions"]'::jsonb),
('revenue_ops', 'Revenue Ops Analyst', 'finance', 'revops_squad', '["Revenue analytics","Billing operations","Subscription metrics"]'::jsonb),
('billing_agent', 'Billing Agent', 'finance', 'revops_squad', '["Invoice generation","Payment processing","Dunning management"]'::jsonb),
('subscription_mgr', 'Subscription Manager', 'finance', 'revops_squad', '["Subscription lifecycle","Plan changes","Renewal processing"]'::jsonb),
('pricing_strategy', 'Pricing Strategy Agent', 'finance', 'revops_squad', '["Pricing optimization","Competitive pricing","Price elasticity"]'::jsonb),
('procurement', 'Procurement Agent', 'finance', 'procurement_squad', '["Purchase orders","Vendor selection","Cost negotiation"]'::jsonb),
('supplier_mgr', 'Supplier Manager', 'finance', 'procurement_squad', '["Supplier evaluation","Performance tracking","Relationship management"]'::jsonb),
('ceo', 'CEO Agent', 'operations', 'executive_squad', '["Strategic planning","OKR management","Cross-department coordination"]'::jsonb),
('orchestrator', 'Orchestrator', 'operations', 'executive_squad', '["Multi-agent coordination","Workflow management","Task delegation"]'::jsonb),
('concierge', 'Concierge', 'operations', 'executive_squad', '["Executive assistance","Calendar management","Priority management"]'::jsonb),
('strategic_planner', 'Strategic Planner', 'operations', 'executive_squad', '["Strategic planning","Market analysis","Growth roadmap"]'::jsonb),
('okr_monitor', 'OKR Monitor', 'operations', 'executive_squad', '["OKR tracking","Progress reporting","Alignment checks"]'::jsonb),
('contract_analyst', 'Contract Analyst', 'operations', 'legal_squad', '["Contract review","Risk assessment","Terms analysis"]'::jsonb),
('compliance_officer', 'Compliance Officer', 'operations', 'legal_squad', '["LGPD compliance","Regulatory adherence","Policy management"]'::jsonb),
('labor_law_agent', 'Labor Law Agent', 'operations', 'legal_squad', '["Labor compliance","eSocial","Employee relations"]'::jsonb),
('legal_researcher', 'Legal Researcher', 'operations', 'legal_squad', '["Legal research","Jurisprudence analysis","Case law"]'::jsonb),
('recruiter_agent', 'Recruiter Agent', 'operations', 'hr_people_squad', '["Talent acquisition","Job postings","Candidate screening"]'::jsonb),
('people_analytics', 'People Analytics', 'operations', 'hr_people_squad', '["HR metrics","Turnover analysis","Engagement surveys"]'::jsonb),
('td_agent', 'T&D Agent', 'operations', 'hr_people_squad', '["Training programs","Skill gaps","Learning paths"]'::jsonb),
('process_analyst', 'Process Analyst', 'operations', 'process_quality_squad', '["Process mapping","Bottleneck identification","Automation opportunities"]'::jsonb),
('quality_auditor', 'Quality Auditor', 'operations', 'process_quality_squad', '["Quality audits","Standard compliance","Corrective actions"]'::jsonb),
('logistics_coordinator', 'Logistics Coordinator', 'operations', 'logistics_supply_squad', '["Shipping management","Route optimization","Delivery tracking"]'::jsonb),
('inventory_manager', 'Inventory Manager', 'operations', 'logistics_supply_squad', '["Stock management","Reorder points","Demand forecasting"]'::jsonb),
('threat_monitor', 'Threat Monitor', 'security', 'cyber_defense_squad', '["Threat detection","Anomaly analysis","Alert triage"]'::jsonb),
('incident_responder', 'Incident Responder', 'security', 'cyber_defense_squad', '["Incident response","Containment","Post-mortem"]'::jsonb),
('vulnerability_scanner', 'Vulnerability Scanner', 'security', 'cyber_defense_squad', '["Vulnerability scanning","Patch management","Risk scoring"]'::jsonb),
('access_auditor', 'Access Auditor', 'security', 'cyber_defense_squad', '["Access reviews","Permission audits","Compliance checks"]'::jsonb),
('gdpr_agent', 'GDPR Agent', 'security', 'compliance_squad', '["GDPR compliance","Data mapping","Consent management"]'::jsonb),
('lgpd_agent', 'LGPD Agent', 'security', 'compliance_squad', '["LGPD compliance","Data protection","Privacy assessments"]'::jsonb),
('soc2_agent', 'SOC2 Agent', 'security', 'compliance_squad', '["SOC2 controls","Evidence collection","Audit preparation"]'::jsonb),
('ci_cd_agent', 'CI/CD Agent', 'engineering', 'devops_squad', '["Pipeline management","Build automation","Deploy orchestration"]'::jsonb),
('infra_agent', 'Infrastructure Agent', 'engineering', 'devops_squad', '["Cloud provisioning","Auto-scaling","Cost optimization"]'::jsonb),
('monitoring_agent', 'Monitoring Agent', 'engineering', 'devops_squad', '["System monitoring","Alert management","Performance tracking"]'::jsonb),
('release_manager', 'Release Manager', 'engineering', 'devops_squad', '["Release planning","Rollback coordination","Feature flags"]'::jsonb),
('test_automation_agent', 'Test Automation Agent', 'engineering', 'qa_squad', '["Test automation","E2E testing","Regression suites"]'::jsonb),
('performance_tester', 'Performance Tester', 'engineering', 'qa_squad', '["Load testing","Stress testing","Bottleneck identification"]'::jsonb),
('security_tester', 'Security Tester', 'engineering', 'qa_squad', '["Penetration testing","Security scanning","Vulnerability assessment"]'::jsonb),
('etl_agent', 'ETL Agent', 'data_analytics', 'data_engineering_squad', '["Data pipelines","ETL processes","Data quality"]'::jsonb),
('data_warehouse_agent', 'Data Warehouse Agent', 'data_analytics', 'data_engineering_squad', '["Warehouse management","Schema design","Query optimization"]'::jsonb),
('data_quality_agent', 'Data Quality Agent', 'data_analytics', 'data_engineering_squad', '["Data validation","Anomaly detection","Quality scoring"]'::jsonb),
('bi_analyst', 'BI Analyst', 'data_analytics', 'bi_squad', '["Dashboard creation","Report automation","Insight generation"]'::jsonb),
('predictive_agent', 'Predictive Analytics Agent', 'data_analytics', 'bi_squad', '["Predictive modeling","Forecasting","Trend analysis"]'::jsonb),
('media_relations_agent', 'Media Relations Agent', 'communications', 'pr_squad', '["Press releases","Media outreach","Interview prep"]'::jsonb),
('crisis_comms_agent', 'Crisis Communications Agent', 'communications', 'pr_squad', '["Crisis management","Response coordination","Stakeholder comms"]'::jsonb),
('social_listening_agent', 'Social Listening Agent', 'communications', 'pr_squad', '["Brand monitoring","Sentiment analysis","Trend spotting"]'::jsonb),
('newsletter_agent', 'Newsletter Agent', 'communications', 'internal_comms_squad', '["Internal newsletters","Company updates","Culture content"]'::jsonb),
('employee_engagement_agent', 'Employee Engagement Agent', 'communications', 'internal_comms_squad', '["Engagement surveys","Pulse checks","Action plans"]'::jsonb),
('sourcing_agent', 'Sourcing Agent', 'talent', 'recruiting_squad', '["Candidate sourcing","Pipeline building","Outreach campaigns"]'::jsonb),
('screening_agent', 'Screening Agent', 'talent', 'recruiting_squad', '["Resume screening","Qualification assessment","Interview scheduling"]'::jsonb),
('employer_brand_agent', 'Employer Brand Agent', 'talent', 'recruiting_squad', '["Employer branding","Careers content","Glassdoor management"]'::jsonb),
('payroll_agent', 'Payroll Agent', 'talent', 'people_ops_squad', '["Payroll processing","Benefits admin","Tax compliance"]'::jsonb),
('performance_agent', 'Performance Agent', 'talent', 'people_ops_squad', '["Performance reviews","Goal tracking","Feedback cycles"]'::jsonb),
('offboarding_agent', 'Offboarding Agent', 'talent', 'people_ops_squad', '["Exit process","Knowledge transfer","Access revocation"]'::jsonb),
('tech_scout', 'Tech Scout', 'innovation', 'research_squad', '["Technology research","Trend analysis","Competitive intel"]'::jsonb),
('prototype_agent', 'Prototype Agent', 'innovation', 'research_squad', '["Rapid prototyping","POC development","Feasibility studies"]'::jsonb),
('patent_agent', 'Patent Agent', 'innovation', 'research_squad', '["Patent research","IP protection","Filing management"]'::jsonb),
('helpdesk_agent', 'Helpdesk Agent', 'it_infrastructure', 'it_support_squad', '["IT support","Ticket resolution","User assistance"]'::jsonb),
('asset_manager', 'Asset Manager', 'it_infrastructure', 'it_support_squad', '["Asset tracking","License management","Procurement"]'::jsonb),
('network_agent', 'Network Agent', 'it_infrastructure', 'it_support_squad', '["Network monitoring","Connectivity issues","VPN management"]'::jsonb),
('cloud_cost_agent', 'Cloud Cost Agent', 'it_infrastructure', 'cloud_ops_squad', '["Cost optimization","Resource rightsizing","Budget alerts"]'::jsonb),
('backup_agent', 'Backup & Recovery Agent', 'it_infrastructure', 'cloud_ops_squad', '["Backup management","Disaster recovery","RTO/RPO monitoring"]'::jsonb),
('market_researcher', 'Market Researcher', 'strategy', 'market_intel_squad', '["Market research","Industry reports","Opportunity sizing"]'::jsonb),
('pricing_strategist', 'Pricing Strategist', 'strategy', 'market_intel_squad', '["Pricing analysis","Elasticity modeling","Revenue optimization"]'::jsonb),
('geo_expansion_agent', 'Geo Expansion Agent', 'strategy', 'expansion_squad', '["Market entry analysis","Localization planning","Regulatory mapping"]'::jsonb),
('m_and_a_analyst', 'M&A Analyst', 'strategy', 'expansion_squad', '["Acquisition analysis","Due diligence","Integration planning"]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, department = EXCLUDED.department, squad = EXCLUDED.squad, responsibilities = EXCLUDED.responsibilities;

-- Hunter LinkedIn: schema completo
UPDATE public.agents_catalog
SET 
  tagline = 'Prospecção automatizada no LinkedIn com IA',
  description = 'Encontra leads qualificados no LinkedIn, gera icebreakers personalizados com IA e envia convites de conexão automaticamente.',
  config_schema = '[
    {"key":"target_audience","label":"Público-alvo","type":"textarea","required":true,"placeholder":"Ex: CTOs e VPs de Engenharia em SaaS B2B com 50-500 funcionários","help":"Descreva o ICP que o agente deve buscar"},
    {"key":"job_titles","label":"Cargos","type":"tags","placeholder":"CTO, VP Engineering, Head of Tech","help":"Cargos a buscar (separe por enter)"},
    {"key":"location","label":"Localização","type":"text","placeholder":"Brasil, São Paulo","help":"País, estado ou cidade"},
    {"key":"linkedin_cookie","label":"Cookie LinkedIn (li_at)","type":"password","required":true,"help":"Cookie de sessão do seu LinkedIn. Configure em Hunter > Configurações."},
    {"key":"daily_limit","label":"Limite diário de convites","type":"slider","min":10,"max":50,"default":20,"help":"Recomendado: 20 para evitar bloqueio"},
    {"key":"icebreaker_template","label":"Template de icebreaker","type":"textarea","placeholder":"Olá {nome}, vi que você é {cargo} na {empresa}...","help":"Use {nome}, {cargo}, {empresa} como variáveis"}
  ]'::jsonb,
  tier = 'pro',
  monthly_price_cents = 99700
WHERE slug = 'hunter_linkedin';
