-- Catálogo de agentes WORKFORCE exposto via MCP Server
CREATE TABLE IF NOT EXISTS public.workforce_agents_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  department text NOT NULL,
  squad text NOT NULL,
  responsibilities text[] NOT NULL DEFAULT '{}',
  triggers text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_workforce_agents_dept ON public.workforce_agents_catalog(department);
CREATE INDEX IF NOT EXISTS idx_workforce_agents_slug ON public.workforce_agents_catalog(slug);

GRANT SELECT ON public.workforce_agents_catalog TO anon, authenticated;
GRANT ALL ON public.workforce_agents_catalog TO service_role;

ALTER TABLE public.workforce_agents_catalog ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "workforce_catalog_public_read" ON public.workforce_agents_catalog;
CREATE POLICY "workforce_catalog_public_read"
  ON public.workforce_agents_catalog FOR SELECT
  TO anon, authenticated
  USING (true);

-- Seed: 208 agentes do workforceArchitecture.ts
INSERT INTO public.workforce_agents_catalog (slug, name, department, squad, responsibilities, triggers) VALUES
('content_strategist','Content Strategist','Marketing','Content Squad','{"Planejamento editorial","Calendário de conteúdo","Análise de gaps"}','{"task_assigned","campaign_launch","monthly_planning"}'),
('blog_writer','Blog Writer','Marketing','Content Squad','{"Artigos SEO","Posts longos","Guest posts"}','{"task_assigned","keyword_opportunity"}'),
('social_media_agent','Social Media Agent','Marketing','Content Squad','{"Posts redes sociais","Engajamento","Calendário social"}','{"scheduled_post","trending_topic","engagement_drop"}'),
('video_script_agent','Video Script Agent','Marketing','Content Squad','{"Roteiros Reels/Shorts","Storyboards","Hooks de vídeo"}','{"task_assigned","video_campaign"}'),
('content_performance','Content Performance Analyst','Marketing','Content Squad','{"Métricas de conteúdo","Attribution","ROI de conteúdo"}','{"report_requested","metric_change","weekly_review"}'),
('media_buyer','Media Buyer','Marketing','Ads Squad','{"Compra de mídia","Budget allocation","Otimização cross-platform"}','{"budget_change","roas_drop","campaign_launch"}'),
('ad_copywriter','Ad Copywriter','Marketing','Ads Squad','{"Copy de anúncios","Headlines A/B","Ad creatives briefing"}','{"task_assigned","ad_fatigue_detected"}'),
('campaign_manager','Campaign Manager','Marketing','Ads Squad','{"Setup de campanhas","Audience targeting","Bid strategy"}','{"campaign_launch","performance_alert"}'),
('retargeting_specialist','Retargeting Specialist','Marketing','Ads Squad','{"Audiências lookalike","Remarketing sequences","Pixel optimization"}','{"cart_abandonment","funnel_drop"}'),
('seo_strategist','SEO Strategist','Marketing','SEO Squad','{"Estratégia SEO global","Keyword research","Roadmap de otimização"}','{"ranking_change","algorithm_update","quarterly_review"}'),
('technical_seo','Technical SEO Agent','Marketing','SEO Squad','{"Core Web Vitals","Crawlability","Schema markup"}','{"site_audit","speed_degradation","indexation_issue"}'),
('link_builder','Link Builder','Marketing','SEO Squad','{"Outreach para backlinks","Digital PR","Guest posting strategy"}','{"task_assigned","competitor_link_gain"}'),
('content_seo_writer','Content SEO Writer','Marketing','SEO Squad','{"Conteúdo otimizado","Topic clusters","Internal linking"}','{"keyword_opportunity","content_gap_found"}'),
('brand_strategist','Brand Strategist','Marketing','Brand Strategy Squad','{"Posicionamento de marca","Brand guidelines","Competitive positioning"}','{"brand_audit","market_shift","quarterly_review"}'),
('positioning_agent','Positioning Agent','Marketing','Brand Strategy Squad','{"Análise de mercado","Diferenciação","Value proposition"}','{"competitor_move","market_research"}'),
('visual_identity','Visual Identity Agent','Marketing','Brand Strategy Squad','{"Design system","Templates visuais","Brand consistency"}','{"campaign_launch","rebrand_request"}'),
('brand_voice_writer','Brand Voice Writer','Marketing','Brand Strategy Squad','{"Tom de voz","Messaging framework","Copy guidelines"}','{"task_assigned","new_channel"}'),
('campaign_optimizer','Campaign Optimizer','Marketing','Campaign Optimization Squad','{"Otimização multicanal","Budget reallocation","Performance tuning"}','{"performance_drop","budget_review","campaign_milestone"}'),
('ab_test_agent','A/B Test Agent','Marketing','Campaign Optimization Squad','{"Design de experimentos","Statistical significance","Test analysis"}','{"test_ready","test_complete","hypothesis_new"}'),
('attribution_analyst','Attribution Analyst','Marketing','Campaign Optimization Squad','{"Multi-touch attribution","Channel mix modeling","Customer journey"}','{"report_requested","conversion_anomaly"}'),
('budget_allocator','Budget Allocator','Marketing','Campaign Optimization Squad','{"Budget optimization","ROI forecasting","Channel efficiency"}','{"budget_cycle","performance_change","monthly_review"}'),
('influencer_mgr','Influencer Manager','Marketing','Influencer & PR Squad','{"Scout de influencers","Negociação","Campaign tracking"}','{"campaign_launch","influencer_match","contract_renewal"}'),
('pr_agent','PR Agent','Marketing','Influencer & PR Squad','{"Press releases","Media relations","Crisis management"}','{"news_event","crisis_detected","launch_scheduled"}'),
('social_proof_mgr','Social Proof Manager','Marketing','Influencer & PR Squad','{"Depoimentos","Case studies","UGC curation"}','{"review_received","milestone_reached","task_assigned"}'),
('traffic_manager','Traffic Manager','Growth','Paid Traffic Squad','{"Gestão de tráfego pago","Cross-platform strategy","Budget optimization"}','{"campaign_launch","roas_change","budget_cycle"}'),
('google_ads_agent','Google Ads Agent','Growth','Paid Traffic Squad','{"Search campaigns","Shopping ads","Display network"}','{"quality_score_drop","keyword_opportunity","bid_adjustment"}'),
('meta_ads_agent','Meta Ads Agent','Growth','Paid Traffic Squad','{"Facebook/Instagram ads","Audience building","Creative testing"}','{"ad_fatigue","audience_saturation","campaign_launch"}'),
('tiktok_ads_agent','TikTok Ads Agent','Growth','Paid Traffic Squad','{"TikTok campaigns","Spark Ads","Creator marketplace"}','{"trending_content","campaign_launch","performance_alert"}'),
('sdr_outbound','SDR Outbound Lead','Growth','SDR Outbound Squad','{"Estratégia outbound","Cadências multicanal","Team coordination"}','{"task_assigned","pipeline_low","quota_review"}'),
('sdr_linkedin','SDR LinkedIn','Growth','SDR Outbound Squad','{"LinkedIn outreach","InMail sequences","Sales Navigator"}','{"lead_match","connection_accepted","profile_viewed"}'),
('sdr_email_agent','SDR Email Agent','Growth','SDR Outbound Squad','{"Cold email sequences","Follow-up automation","Deliverability"}','{"lead_assigned","email_opened","reply_received"}'),
('sdr_whatsapp','SDR WhatsApp','Growth','SDR Outbound Squad','{"WhatsApp outreach","Qualificação rápida","Follow-up sequences"}','{"lead_assigned","message_read","response_timeout"}'),
('sdr_instagram','SDR Instagram','Growth','SDR Outbound Squad','{"DM outreach","Story engagement","Social selling"}','{"lead_match","story_viewed","engagement_signal"}'),
('sdr_inbound','SDR Inbound Lead','Growth','SDR Inbound Squad','{"Lead routing","Qualification framework","SLA management"}','{"lead_received","form_submission","chat_initiated"}'),
('lead_qualifier','Lead Qualifier','Growth','SDR Inbound Squad','{"BANT qualification","Discovery calls","Lead scoring refinement"}','{"new_lead","score_threshold","qualification_needed"}'),
('lead_scorer','Lead Scorer','Growth','SDR Inbound Squad','{"Lead scoring models","Behavioral tracking","Score calibration"}','{"activity_detected","page_visited","content_downloaded"}'),
('mql_processor','MQL Processor','Growth','SDR Inbound Squad','{"MQL validation","Data enrichment","CRM handoff"}','{"score_threshold_reached","mql_criteria_met"}'),
('partnership_hunter','Partnership Hunter','Growth','Partnerships Squad','{"Identificação de parceiros","Outreach","Negociação"}','{"market_opportunity","task_assigned","quarterly_review"}'),
('affiliate_manager','Affiliate Manager','Growth','Partnerships Squad','{"Programa de afiliados","Comissões","Performance tracking"}','{"affiliate_signup","commission_threshold","performance_review"}'),
('comarketing_agent','Co-Marketing Agent','Growth','Partnerships Squad','{"Campanhas conjuntas","Webinars","Content collaboration"}','{"partner_aligned","campaign_scheduled","co_branded_content"}'),
('plg_strategist','PLG Strategist','Growth','Product-Led Growth Squad','{"Growth strategy","Viral loops","Freemium optimization"}','{"metric_change","experiment_complete","quarterly_planning"}'),
('onboarding_optimizer','Onboarding Optimizer','Growth','Product-Led Growth Squad','{"Onboarding flows","Activation metrics","First value time"}','{"signup_detected","activation_drop","funnel_bottleneck"}'),
('activation_agent','Activation Agent','Growth','Product-Led Growth Squad','{"Feature adoption","Aha moment triggers","User nudges"}','{"user_inactive","feature_unused","milestone_missed"}'),
('retention_analyst','Retention Analyst','Growth','Product-Led Growth Squad','{"Cohort analysis","Churn prediction","Retention campaigns"}','{"churn_risk_detected","cohort_degradation","monthly_review"}'),
('community_mgr','Community Manager','Growth','Community Squad','{"Gestão de comunidade","Engagement programs","Member onboarding"}','{"member_joined","engagement_drop","event_scheduled"}'),
('forum_moderator','Forum Moderator','Growth','Community Squad','{"Moderação","Content quality","Community guidelines"}','{"post_flagged","new_discussion","rule_violation"}'),
('ambassador_agent','Ambassador Program Agent','Growth','Community Squad','{"Programa de embaixadores","Recognition","Advocacy"}','{"ambassador_nominated","milestone_reached","quarterly_review"}'),
('ugc_curator','UGC Curator','Growth','Community Squad','{"User-generated content","Showcase","Permissions"}','{"ugc_submitted","campaign_need","content_gap"}'),
('product_strategist','Product Strategist','Product','Product Strategy Squad','{"Product vision","Roadmap planning","Stakeholder alignment"}','{"quarterly_planning","market_shift","user_feedback_surge"}'),
('roadmap_manager','Roadmap Manager','Product','Product Strategy Squad','{"Roadmap updates","Timeline tracking","Dependency mapping"}','{"milestone_reached","delay_detected","stakeholder_request"}'),
('competitive_analyst','Competitive Analyst','Product','Product Strategy Squad','{"Competitor monitoring","Feature comparison","Market gaps"}','{"competitor_launch","market_report","quarterly_review"}'),
('market_research_agent','Market Research Agent','Product','Product Strategy Squad','{"User interviews analysis","Market sizing","Trend analysis"}','{"research_needed","new_market_entry","product_launch"}'),
('ux_researcher','UX Researcher','Product','UX Research Squad','{"Research planning","Study design","Insights synthesis"}','{"research_needed","usability_issue","feature_planning"}'),
('user_interview_agent','User Interview Agent','Product','UX Research Squad','{"Interview scripts","User recruitment","Transcription analysis"}','{"interview_scheduled","research_sprint","feedback_needed"}'),
('survey_analyst','Survey Analyst','Product','UX Research Squad','{"Survey design","Data analysis","Statistical insights"}','{"survey_completed","feedback_collected","quarterly_review"}'),
('usability_tester','Usability Tester','Product','UX Research Squad','{"Usability tests","Heuristic evaluation","Accessibility audit"}','{"feature_ready","ux_complaint","release_candidate"}'),
('product_data_analyst','Data Analyst','Product','Data & Analytics Squad','{"Product analytics","Dashboard creation","Trend identification"}','{"report_requested","anomaly_detected","weekly_review"}'),
('product_metrics_agent','Product Metrics Agent','Product','Data & Analytics Squad','{"KPI tracking","North star metric","Feature metrics"}','{"metric_change","goal_deviation","sprint_review"}'),
('cohort_analyst','Cohort Analyst','Product','Data & Analytics Squad','{"Cohort analysis","Retention curves","Behavioral segmentation"}','{"cohort_complete","retention_drop","monthly_review"}'),
('funnel_analyst','Funnel Analyst','Product','Data & Analytics Squad','{"Conversion funnels","Drop-off analysis","Optimization recommendations"}','{"conversion_drop","funnel_change","ab_test_complete"}'),
('experimentation_agent','Experimentation Agent','Product','Data & Analytics Squad','{"A/B test design","Feature flags","Statistical analysis"}','{"experiment_proposed","test_complete","feature_rollout"}'),
('technical_writer','Technical Writer','Product','Engineering Support Squad','{"Documentation","API docs","Knowledge base"}','{"feature_shipped","doc_outdated","api_change"}'),
('api_doc_agent','API Documentation Agent','Product','Engineering Support Squad','{"API reference","Code examples","SDK guides"}','{"api_version_released","endpoint_added","doc_request"}'),
('qa_analyst','QA Analyst','Product','Engineering Support Squad','{"Test planning","Bug verification","Regression testing"}','{"release_candidate","bug_reported","sprint_complete"}'),
('bug_tracker','Bug Tracker','Product','Engineering Support Squad','{"Bug triage","Priority classification","Resolution tracking"}','{"bug_reported","severity_escalation","sprint_planning"}'),
('release_notes_agent','Release Notes Agent','Product','Engineering Support Squad','{"Changelog generation","Release communications","Feature announcements"}','{"release_deployed","feature_launched","hotfix_applied"}'),
('ai_research_agent','AI Research Agent','Product','AI & Innovation Squad','{"Model evaluation","Capability assessment","Research papers"}','{"new_model_released","capability_gap","quarterly_review"}'),
('trend_scout','Trend Scout','Product','AI & Innovation Squad','{"Technology trends","Market signals","Early adoption"}','{"trend_detected","competitor_innovation","monthly_scan"}'),
('innovation_lab','Innovation Lab Agent','Product','AI & Innovation Squad','{"Proof of concepts","Prototype development","Feasibility analysis"}','{"poc_requested","innovation_sprint","opportunity_identified"}'),
('prototype_tester','Prototype Tester','Product','AI & Innovation Squad','{"Prototype testing","User feedback","Iteration recommendations"}','{"prototype_ready","test_scheduled","feedback_collected"}'),
('tech_evaluator','Technology Evaluator','Product','AI & Innovation Squad','{"Vendor assessment","Tool comparison","Build vs buy analysis"}','{"tool_needed","vendor_pitch","architecture_review"}'),
('enterprise_ae','Enterprise Account Executive','Sales','Enterprise Sales Squad','{"Enterprise deals","Stakeholder mapping","Proposal customization"}','{"deal_stage_change","meeting_scheduled","contract_sent"}'),
('solution_architect','Solution Architect','Sales','Enterprise Sales Squad','{"Technical discovery","Solution design","Integration planning"}','{"technical_call","rfp_received","poc_requested"}'),
('proposal_gen','Proposal Generator','Sales','Enterprise Sales Squad','{"Proposal creation","Pricing models","ROI calculations"}','{"deal_qualified","proposal_requested","renewal_approaching"}'),
('contract_negotiator','Contract Negotiator','Sales','Enterprise Sales Squad','{"Contract terms","Legal review","SLA negotiation"}','{"contract_stage","redline_received","negotiation_stalled"}'),
('midmarket_ae','Mid-Market AE','Sales','Mid-Market Sales Squad','{"Mid-market deals","Demo execution","Pipeline management"}','{"deal_assigned","demo_scheduled","follow_up_due"}'),
('demo_specialist','Demo Specialist','Sales','Mid-Market Sales Squad','{"Demo preparation","Use case customization","Demo follow-up"}','{"demo_scheduled","deal_stage_discovery","competitor_mentioned"}'),
('pricing_analyst','Pricing Analyst','Sales','Mid-Market Sales Squad','{"Pricing strategy","Discount approval","Competitive pricing"}','{"quote_requested","discount_needed","competitor_pricing"}'),
('deal_desk','Deal Desk Agent','Sales','Mid-Market Sales Squad','{"Deal structuring","Approval workflow","Contract generation"}','{"deal_approval_needed","non_standard_deal","contract_requested"}'),
('smb_closer','SMB Closer','Sales','SMB Sales Squad','{"High-velocity closing","Objection handling","Quick proposals"}','{"lead_qualified","trial_ending","interest_signal"}'),
('self_serve_optimizer','Self-Serve Optimizer','Sales','SMB Sales Squad','{"Checkout optimization","Friction removal","Payment flows"}','{"checkout_abandonment","conversion_drop","pricing_page_visit"}'),
('trial_converter','Trial Converter','Sales','SMB Sales Squad','{"Trial engagement","Feature adoption nudges","Conversion incentives"}','{"trial_started","trial_midpoint","trial_expiring"}'),
('upgrade_agent','Upgrade Agent','Sales','SMB Sales Squad','{"Upsell opportunities","Plan comparison","Value demonstration"}','{"usage_threshold","feature_limit_hit","renewal_approaching"}'),
('crm_manager','CRM Manager','Sales','Sales Operations Squad','{"CRM hygiene","Automation workflows","Data integrity"}','{"data_quality_issue","workflow_error","integration_needed"}'),
('sales_forecaster','Sales Forecaster','Sales','Sales Operations Squad','{"Revenue forecasting","Pipeline analysis","Trend modeling"}','{"forecast_deadline","pipeline_change","quarterly_review"}'),
('territory_planner','Territory Planner','Sales','Sales Operations Squad','{"Territory design","Quota setting","Balance optimization"}','{"territory_review","rep_change","market_expansion"}'),
('sales_enablement','Sales Enablement Agent','Sales','Sales Operations Squad','{"Sales collateral","Training content","Competitive cards"}','{"new_feature","competitor_update","onboarding_new_rep"}'),
('hunter_linkedin','Hunter - Prospecção LinkedIn','Sales','Sales Operations Squad','{"Busca de leads no LinkedIn","Icebreakers com IA","Envio automático de convites"}','{"campanha_criada","leads_encontrados","lead_respondeu"}'),
('channel_manager','Channel Manager','Sales','Channel Sales Squad','{"Channel strategy","Partner relationships","Revenue tracking"}','{"partner_deal","channel_review","revenue_target"}'),
('reseller_recruiter','Reseller Recruiter','Sales','Channel Sales Squad','{"Reseller identification","Onboarding","Certification"}','{"market_gap","partner_pipeline","recruitment_target"}'),
('channel_revenue','Channel Revenue Analyst','Sales','Channel Sales Squad','{"Channel analytics","Partner performance","ROI analysis"}','{"report_requested","performance_review","quarterly_review"}'),
('voice_ai','Voice AI Agent','Sales','Voice & Telephony Squad','{"AI voice calls","Natural conversation","Intent detection"}','{"call_scheduled","lead_priority","follow_up_needed"}'),
('call_analyzer','Call Analyzer','Sales','Voice & Telephony Squad','{"Call transcription","Sentiment analysis","Coaching insights"}','{"call_completed","coaching_review","quality_audit"}'),
('script_optimizer','Script Optimizer','Sales','Voice & Telephony Squad','{"Script testing","Objection handling","Conversion optimization"}','{"low_conversion","new_product","ab_test_result"}'),
('revenue_analyst','Revenue Analyst','Sales','Revenue Intelligence Squad','{"Revenue analytics","MRR/ARR tracking","Revenue trends"}','{"report_requested","revenue_anomaly","monthly_close"}'),
('winloss_analyst','Win/Loss Analyst','Sales','Revenue Intelligence Squad','{"Win/loss analysis","Competitive patterns","Deal insights"}','{"deal_closed_lost","deal_closed_won","quarterly_review"}'),
('onboarding_specialist','Onboarding Specialist','Customer Success','Onboarding Squad','{"Onboarding planning","Kickoff calls","Milestone tracking"}','{"customer_signed","onboarding_started","milestone_missed"}'),
('implementation_agent','Implementation Agent','Customer Success','Onboarding Squad','{"Technical setup","Data migration","Integration config"}','{"setup_started","integration_needed","blocker_identified"}'),
('training_agent','Training Agent','Customer Success','Onboarding Squad','{"User training","Workshop facilitation","Training materials"}','{"training_scheduled","new_user_added","feature_released"}'),
('support_channel','Support Channel Agent','Customer Success','Support N1 Squad','{"Multi-channel support","Ticket routing","First response"}','{"ticket_created","chat_initiated","email_received"}'),
('chat_agent','Chat Agent','Customer Success','Support N1 Squad','{"Live chat","Instant responses","Quick resolution"}','{"chat_started","visitor_question","pre_sale_inquiry"}'),
('email_support','Email Support Agent','Customer Success','Support N1 Squad','{"Email support","Detailed responses","Follow-up tracking"}','{"email_received","ticket_escalated","response_due"}'),
('support_lead','Technical Support Lead','Customer Success','Support N2/N3 Squad','{"Complex troubleshooting","Escalation management","Team coordination"}','{"escalation_received","complex_issue","vip_customer"}'),
('escalation_mgr','Escalation Manager','Customer Success','Support N2/N3 Squad','{"Escalation workflow","Resolution tracking","Communication"}','{"sla_breach","customer_escalation","executive_complaint"}'),
('bug_reporter','Bug Reporter Agent','Customer Success','Support N2/N3 Squad','{"Bug documentation","Reproduction steps","Engineering handoff"}','{"bug_confirmed","regression_found","critical_issue"}'),
('integration_support','Integration Support Agent','Customer Success','Support N2/N3 Squad','{"Integration troubleshooting","API support","Webhook debugging"}','{"integration_error","api_question","webhook_failure"}'),
('sla_monitor','SLA Monitor','Customer Success','Support N2/N3 Squad','{"SLA tracking","Breach prevention","Performance reporting"}','{"sla_warning","breach_imminent","report_requested"}'),
('csm_agent','CSM Agent','Customer Success','Success Management Squad','{"Account management","Success planning","Relationship building"}','{"account_review_due","health_score_change","renewal_approaching"}'),
('health_monitor','Health Score Monitor','Customer Success','Success Management Squad','{"Health scoring","Risk identification","Intervention triggers"}','{"score_drop","usage_decline","daily_monitoring"}'),
('expansion_agent','Expansion Agent','Customer Success','Success Management Squad','{"Upsell identification","Cross-sell opportunities","Value realization"}','{"usage_threshold","feature_request","expansion_signal"}'),
('renewal_agent','Renewal Agent','Customer Success','Success Management Squad','{"Renewal management","Contract terms","Retention offers"}','{"renewal_90_days","renewal_30_days","churn_risk"}'),
('ebr_agent','Executive Business Review Agent','Customer Success','Success Management Squad','{"QBR preparation","ROI reporting","Strategic recommendations"}','{"qbr_scheduled","quarterly_cycle","executive_request"}'),
('knowledge_base_agent','Knowledge Base Agent','Customer Success','Knowledge & Self-Service Squad','{"KB management","Article creation","Content updates"}','{"article_outdated","gap_identified","feature_released"}'),
('help_center_writer','Help Center Writer','Customer Success','Knowledge & Self-Service Squad','{"How-to guides","Troubleshooting articles","Video tutorials"}','{"article_needed","common_ticket","feature_launched"}'),
('tutorial_creator','Tutorial Creator','Customer Success','Knowledge & Self-Service Squad','{"Step-by-step tutorials","Interactive guides","Walkthrough videos"}','{"feature_released","onboarding_need","user_confusion"}'),
('chatbot_trainer','Chatbot Trainer','Customer Success','Knowledge & Self-Service Squad','{"Chatbot training","Intent mapping","Response optimization"}','{"low_resolution","new_intent","feedback_received"}'),
('selfservice_optimizer','Self-Service Optimizer','Customer Success','Knowledge & Self-Service Squad','{"Self-service metrics","Deflection optimization","User experience"}','{"deflection_drop","search_failure","monthly_review"}'),
('nps_analyst','NPS Analyst','Customer Success','Voice of Customer Squad','{"NPS campaigns","Score analysis","Follow-up actions"}','{"survey_completed","score_drop","quarterly_review"}'),
('csat_monitor','CSAT Monitor','Customer Success','Voice of Customer Squad','{"CSAT tracking","Trend analysis","Alert management"}','{"low_csat","trend_change","daily_monitoring"}'),
('feedback_collector','Feedback Collector','Customer Success','Voice of Customer Squad','{"Feedback collection","Categorization","Product team handoff"}','{"feedback_submitted","interview_complete","feature_review"}'),
('customer_advocacy','Customer Advocacy Agent','Customer Success','Voice of Customer Squad','{"Case studies","Testimonials","Reference program"}','{"success_story","high_nps","reference_needed"}'),
('digital_accountant','Digital Accountant','Finance','Accounting Squad','{"Escrituração contábil","Conciliação bancária","Balancete"}','{"transaction_recorded","reconciliation_due","monthly_close"}'),
('accounts_payable','Accounts Payable Agent','Finance','Accounting Squad','{"Contas a pagar","Vendor payments","Cash flow management"}','{"invoice_received","payment_due","approval_needed"}'),
('accounts_receivable','Accounts Receivable Agent','Finance','Accounting Squad','{"Contas a receber","Collections","Aging analysis"}','{"invoice_sent","payment_overdue","aging_report"}'),
('reconciliation_agent','Reconciliation Agent','Finance','Accounting Squad','{"Bank reconciliation","GL matching","Discrepancy resolution"}','{"statement_received","mismatch_detected","daily_reconciliation"}'),
('general_ledger','General Ledger Agent','Finance','Accounting Squad','{"GL maintenance","Journal entries","Period closing"}','{"entry_posted","period_close","audit_request"}'),
('tax_compliance','Tax Compliance Agent','Finance','Tax & Compliance Squad','{"Obrigações acessórias","SPED/EFD","Apuração de impostos"}','{"deadline_approaching","legislation_change","monthly_filing"}'),
('tax_content_agent','Tax Content Writer','Finance','Tax & Compliance Squad','{"Conteúdo tributário","Alertas fiscais","Newsletter fiscal"}','{"legislation_change","content_scheduled","client_question"}'),
('regulatory_monitor','Regulatory Monitor','Finance','Tax & Compliance Squad','{"Regulatory tracking","Compliance alerts","Impact analysis"}','{"regulation_published","deadline_approaching","industry_change"}'),
('audit_prep','Audit Preparation Agent','Finance','Tax & Compliance Squad','{"Audit documentation","Evidence collection","Compliance testing"}','{"audit_scheduled","evidence_request","compliance_gap"}'),
('fiscal_analyst','Fiscal Analyst','Finance','Tax & Compliance Squad','{"Tax optimization","Credit identification","Fiscal planning"}','{"quarterly_review","credit_opportunity","planning_cycle"}'),
('ai_cfo','CFO Agent','Finance','FP&A Squad','{"Financial strategy","Board reporting","Capital allocation"}','{"board_meeting","strategic_decision","quarterly_review"}'),
('budget_analyst','Budget Analyst','Finance','FP&A Squad','{"Budget creation","Variance analysis","Departmental budgets"}','{"budget_cycle","variance_threshold","reforecast_needed"}'),
('financial_forecaster','Financial Forecaster','Finance','FP&A Squad','{"Revenue forecasting","Scenario modeling","Cash flow projection"}','{"forecast_cycle","market_change","data_update"}'),
('variance_analyst','Variance Analyst','Finance','FP&A Squad','{"Actual vs budget","Root cause analysis","Corrective actions"}','{"period_close","variance_detected","management_request"}'),
('revenue_ops','Revenue Ops Analyst','Finance','Revenue Operations Squad','{"Revenue analytics","Billing operations","Subscription metrics"}','{"mrr_change","billing_error","monthly_review"}'),
('billing_agent','Billing Agent','Finance','Revenue Operations Squad','{"Invoice generation","Payment processing","Dunning management"}','{"billing_cycle","payment_failed","subscription_change"}'),
('subscription_mgr','Subscription Manager','Finance','Revenue Operations Squad','{"Subscription lifecycle","Plan changes","Renewal processing"}','{"subscription_event","plan_change","renewal_due"}'),
('pricing_strategy','Pricing Strategy Agent','Finance','Revenue Operations Squad','{"Pricing optimization","Competitive pricing","Price elasticity"}','{"market_analysis","competitor_pricing","quarterly_review"}'),
('procurement','Procurement Agent','Finance','Procurement Squad','{"Purchase orders","Vendor selection","Cost negotiation"}','{"purchase_request","contract_renewal","budget_allocated"}'),
('supplier_mgr','Supplier Manager','Finance','Procurement Squad','{"Supplier evaluation","Performance tracking","Relationship management"}','{"supplier_review","quality_issue","contract_expiring"}'),
('ceo','CEO Agent','Operations','Executive Squad','{"Strategic planning","OKR management","Cross-department coordination"}','{"strategic_decision","okr_review","escalation_critical"}'),
('orchestrator','Orchestrator','Operations','Executive Squad','{"Multi-agent coordination","Workflow management","Task delegation"}','{"complex_task","cross_department","automation_trigger"}'),
('concierge','Concierge','Operations','Executive Squad','{"Executive assistance","Calendar management","Priority management"}','{"request_received","schedule_conflict","priority_change"}'),
('strategic_planner','Strategic Planner','Operations','Executive Squad','{"Strategic planning","Market analysis","Growth roadmap"}','{"planning_cycle","market_shift","board_request"}'),
('okr_monitor','OKR Monitor','Operations','Executive Squad','{"OKR tracking","Progress reporting","Alignment checks"}','{"okr_update","progress_review","quarterly_close"}'),
('contract_analyst','Contract Analyst','Operations','Legal Squad','{"Contract review","Risk assessment","Terms analysis"}','{"contract_received","review_requested","deadline_approaching"}'),
('compliance_officer','Compliance Officer','Operations','Legal Squad','{"LGPD compliance","Regulatory adherence","Policy management"}','{"regulation_change","audit_scheduled","compliance_gap"}'),
('labor_law_agent','Labor Law Agent','Operations','Legal Squad','{"Labor compliance","eSocial","Employee relations"}','{"hr_event","legislation_change","dispute_filed"}'),
('legal_researcher','Legal Researcher','Operations','Legal Squad','{"Legal research","Jurisprudence analysis","Case law"}','{"research_needed","legal_question","case_preparation"}'),
('recruiter_agent','Recruiter Agent','Operations','HR & People Squad','{"Talent acquisition","Job postings","Candidate screening"}','{"position_opened","application_received","interview_scheduled"}'),
('people_analytics','People Analytics','Operations','HR & People Squad','{"HR metrics","Turnover analysis","Engagement surveys"}','{"survey_completed","turnover_spike","quarterly_review"}'),
('td_agent','T&D Agent','Operations','HR & People Squad','{"Training programs","Skill gaps","Learning paths"}','{"training_needed","new_hire","skill_assessment"}'),
('process_analyst','Process Analyst','Operations','Process & Quality Squad','{"Process mapping","Bottleneck identification","Automation opportunities"}','{"process_review","inefficiency_detected","improvement_request"}'),
('quality_auditor','Quality Auditor','Operations','Process & Quality Squad','{"Quality audits","Standard compliance","Corrective actions"}','{"audit_scheduled","quality_issue","certification_review"}'),
('logistics_coordinator','Logistics Coordinator','Operations','Logistics & Supply Chain Squad','{"Shipping management","Route optimization","Delivery tracking"}','{"order_placed","delivery_issue","route_optimization"}'),
('inventory_manager','Inventory Manager','Operations','Logistics & Supply Chain Squad','{"Stock management","Reorder points","Demand forecasting"}','{"stock_low","demand_change","inventory_audit"}'),
('threat_monitor','Threat Monitor','Segurança & Compliance','Cyber Defense Squad','{"Threat detection","Anomaly analysis","Alert triage"}','{"anomaly_detected","alert_fired","scan_complete"}'),
('incident_responder','Incident Responder','Segurança & Compliance','Cyber Defense Squad','{"Incident response","Containment","Post-mortem"}','{"incident_created","severity_escalation","containment_needed"}'),
('vulnerability_scanner','Vulnerability Scanner','Segurança & Compliance','Cyber Defense Squad','{"Vulnerability scanning","Patch management","Risk scoring"}','{"scan_scheduled","cve_published","deploy_completed"}'),
('access_auditor','Access Auditor','Segurança & Compliance','Cyber Defense Squad','{"Access reviews","Permission audits","Compliance checks"}','{"review_scheduled","permission_change","audit_requested"}'),
('gdpr_agent','GDPR Agent','Segurança & Compliance','Compliance Squad','{"GDPR compliance","Data mapping","Consent management"}','{"data_request","consent_change","audit_scheduled"}'),
('lgpd_agent','LGPD Agent','Segurança & Compliance','Compliance Squad','{"LGPD compliance","Data protection","Privacy assessments"}','{"data_processing","privacy_request","regulation_update"}'),
('soc2_agent','SOC2 Agent','Segurança & Compliance','Compliance Squad','{"SOC2 controls","Evidence collection","Audit preparation"}','{"control_review","audit_approaching","evidence_needed"}'),
('ci_cd_agent','CI/CD Agent','Engenharia','DevOps Squad','{"Pipeline management","Build automation","Deploy orchestration"}','{"push_event","pr_merged","build_failed"}'),
('infra_agent','Infrastructure Agent','Engenharia','DevOps Squad','{"Cloud provisioning","Auto-scaling","Cost optimization"}','{"capacity_threshold","cost_alert","infra_request"}'),
('monitoring_agent','Monitoring Agent','Engenharia','DevOps Squad','{"System monitoring","Alert management","Performance tracking"}','{"metric_anomaly","alert_triggered","health_check"}'),
('release_manager','Release Manager','Engenharia','DevOps Squad','{"Release planning","Rollback coordination","Feature flags"}','{"release_scheduled","rollback_needed","feature_toggle"}'),
('test_automation_agent','Test Automation Agent','Engenharia','QA & Testing Squad','{"Test automation","E2E testing","Regression suites"}','{"code_change","release_candidate","bug_reported"}'),
('performance_tester','Performance Tester','Engenharia','QA & Testing Squad','{"Load testing","Stress testing","Bottleneck identification"}','{"pre_release","performance_alert","scale_event"}'),
('security_tester','Security Tester','Engenharia','QA & Testing Squad','{"Penetration testing","Security scanning","Vulnerability assessment"}','{"deploy_completed","security_review","new_feature"}'),
('etl_agent','ETL Agent','Data & Analytics','Data Engineering Squad','{"Data pipelines","ETL processes","Data quality"}','{"pipeline_scheduled","data_error","source_added"}'),
('data_warehouse_agent','Data Warehouse Agent','Data & Analytics','Data Engineering Squad','{"Warehouse management","Schema design","Query optimization"}','{"schema_change","query_slow","storage_threshold"}'),
('data_quality_agent','Data Quality Agent','Data & Analytics','Data Engineering Squad','{"Data validation","Anomaly detection","Quality scoring"}','{"ingestion_complete","quality_alert","validation_failed"}'),
('bi_analyst','BI Analyst','Data & Analytics','Business Intelligence Squad','{"Dashboard creation","Report automation","Insight generation"}','{"report_requested","metric_anomaly","period_close"}'),
('predictive_agent','Predictive Analytics Agent','Data & Analytics','Business Intelligence Squad','{"Predictive modeling","Forecasting","Trend analysis"}','{"model_scheduled","data_updated","forecast_requested"}'),
('ab_test_agent','A/B Test Agent','Data & Analytics','Business Intelligence Squad','{"Experiment design","Statistical analysis","Winner selection"}','{"experiment_created","sample_reached","test_concluded"}'),
('media_relations_agent','Media Relations Agent','Comunicação & PR','Public Relations Squad','{"Press releases","Media outreach","Interview prep"}','{"news_event","press_request","launch_scheduled"}'),
('crisis_comms_agent','Crisis Communications Agent','Comunicação & PR','Public Relations Squad','{"Crisis management","Response coordination","Stakeholder comms"}','{"crisis_detected","negative_press","incident_public"}'),
('social_listening_agent','Social Listening Agent','Comunicação & PR','Public Relations Squad','{"Brand monitoring","Sentiment analysis","Trend spotting"}','{"mention_spike","sentiment_shift","competitor_news"}'),
('newsletter_agent','Newsletter Agent','Comunicação & PR','Internal Communications Squad','{"Internal newsletters","Company updates","Culture content"}','{"update_scheduled","milestone_achieved","announcement_needed"}'),
('employee_engagement_agent','Employee Engagement Agent','Comunicação & PR','Internal Communications Squad','{"Engagement surveys","Pulse checks","Action plans"}','{"survey_scheduled","engagement_drop","feedback_received"}'),
('sourcing_agent','Sourcing Agent','Talent & People','Recruiting Squad','{"Candidate sourcing","Pipeline building","Outreach campaigns"}','{"role_opened","pipeline_low","referral_received"}'),
('screening_agent','Screening Agent','Talent & People','Recruiting Squad','{"Resume screening","Qualification assessment","Interview scheduling"}','{"application_received","screening_queue","interview_requested"}'),
('employer_brand_agent','Employer Brand Agent','Talent & People','Recruiting Squad','{"Employer branding","Careers content","Glassdoor management"}','{"review_posted","content_scheduled","campaign_launch"}'),
('payroll_agent','Payroll Agent','Talent & People','People Ops Squad','{"Payroll processing","Benefits admin","Tax compliance"}','{"payroll_cycle","benefit_change","tax_deadline"}'),
('performance_agent','Performance Agent','Talent & People','People Ops Squad','{"Performance reviews","Goal tracking","Feedback cycles"}','{"review_cycle","goal_deadline","feedback_due"}'),
('offboarding_agent','Offboarding Agent','Talent & People','People Ops Squad','{"Exit process","Knowledge transfer","Access revocation"}','{"resignation_received","termination_approved","last_day_approaching"}'),
('tech_scout','Tech Scout','Inovação & R&D','Research Squad','{"Technology research","Trend analysis","Competitive intel"}','{"research_scheduled","tech_trend","competitor_launch"}'),
('prototype_agent','Prototype Agent','Inovação & R&D','Research Squad','{"Rapid prototyping","POC development","Feasibility studies"}','{"idea_approved","prototype_requested","poc_deadline"}'),
('patent_agent','Patent Agent','Inovação & R&D','Research Squad','{"Patent research","IP protection","Filing management"}','{"invention_disclosed","patent_search","filing_deadline"}'),
('helpdesk_agent','Helpdesk Agent','IT & Infraestrutura','IT Support Squad','{"IT support","Ticket resolution","User assistance"}','{"ticket_created","user_request","system_issue"}'),
('asset_manager','Asset Manager','IT & Infraestrutura','IT Support Squad','{"Asset tracking","License management","Procurement"}','{"asset_request","license_expiring","inventory_review"}'),
('network_agent','Network Agent','IT & Infraestrutura','IT Support Squad','{"Network monitoring","Connectivity issues","VPN management"}','{"network_alert","connectivity_issue","config_change"}'),
('cloud_cost_agent','Cloud Cost Agent','IT & Infraestrutura','Cloud Operations Squad','{"Cost optimization","Resource rightsizing","Budget alerts"}','{"cost_spike","budget_threshold","monthly_review"}'),
('backup_agent','Backup & Recovery Agent','IT & Infraestrutura','Cloud Operations Squad','{"Backup management","Disaster recovery","RTO/RPO monitoring"}','{"backup_scheduled","recovery_test","failure_detected"}'),
('competitive_analyst','Competitive Analyst','Estratégia & Inteligência','Market Intelligence Squad','{"Competitive analysis","Market mapping","Threat assessment"}','{"competitor_update","market_shift","strategy_review"}'),
('market_researcher','Market Researcher','Estratégia & Inteligência','Market Intelligence Squad','{"Market research","Industry reports","Opportunity sizing"}','{"research_requested","industry_event","quarterly_review"}'),
('pricing_strategist','Pricing Strategist','Estratégia & Inteligência','Market Intelligence Squad','{"Pricing analysis","Elasticity modeling","Revenue optimization"}','{"pricing_review","competitor_price_change","margin_alert"}'),
('geo_expansion_agent','Geo Expansion Agent','Estratégia & Inteligência','Expansion & New Markets Squad','{"Market entry analysis","Localization planning","Regulatory mapping"}','{"expansion_proposed","market_validated","regulatory_change"}'),
('m_and_a_analyst','M&A Analyst','Estratégia & Inteligência','Expansion & New Markets Squad','{"Acquisition analysis","Due diligence","Integration planning"}','{"target_identified","dd_started","deal_stage_change"}'),
('captacao_juridica','Especialista em Captação Jurídica','Advocacia','Squad de Captação & Atendimento Jurídico','{"Captação de leads via WhatsApp e landing pages","Qualificação inicial do caso","Agendamento de atendimento com o advogado"}','{"lead_recebido","form_preenchido","mensagem_whatsapp"}'),
('diagnostico_juridico','Consultor de Diagnóstico Jurídico','Advocacia','Squad de Captação & Atendimento Jurídico','{"Pré-atendimento estruturado","Identificação da área do direito","Educação do cliente sobre o processo"}','{"lead_qualificado","atendimento_iniciado"}'),
('risco_contratual','Analista de Risco Contratual','Advocacia','Squad de Captação & Atendimento Jurídico','{"Leitura e análise de contratos","Identificação de cláusulas críticas","Relatório de riscos para o advogado revisar"}','{"documento_enviado","contrato_recebido"}'),
('fechamento_juridico','Especialista em Fechamento Jurídico','Advocacia','Squad de Captação & Atendimento Jurídico','{"Geração de propostas personalizadas","Apresentação de honorários","Condução do lead até a contratação"}','{"diagnostico_concluido","proposta_solicitada"}'),
('recuperacao_leads_juridico','Gestor de Recuperação de Leads','Advocacia','Squad de Captação & Atendimento Jurídico','{"Follow-ups automáticos e humanizados","Reativação de leads frios","Reagendamentos"}','{"lead_inativo_72h","proposta_sem_resposta","no_show"}'),
('producao_juridica','Assistente de Produção Jurídica','Advocacia','Squad de Captação & Atendimento Jurídico','{"Apoio na elaboração de minutas e peças","Organização de documentos do caso","Pesquisa de jurisprudência (validação humana obrigatória)"}','{"peca_solicitada","caso_aberto"}'),
('assistente_juridico_operacional','Assistente Jurídico Operacional','Advocacia','Squad de Captação & Atendimento Jurídico','{"Análise de contratos e relatório de risco","Geração de propostas de honorários (fixo/êxito/híbrido)","Apoio ao fechamento e pré-triagem KYC/LGPD/PLD"}','{"contrato_para_analise","proposta_solicitada","fechamento_em_andamento"}')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  department = EXCLUDED.department,
  squad = EXCLUDED.squad,
  responsibilities = EXCLUDED.responsibilities,
  triggers = EXCLUDED.triggers,
  updated_at = now();
